build:
  nodes:
    coverage:
      environment:
        php: 7.2
      tests:
        override:
        - command: bin/phpspec run
          coverage:
            file: doc/coverage.xml
            format: clover
