build:
  nodes:
    coverage:
      tests:
        override:
        - command: bin/phpspec run
          coverage:
            file: doc/coverage.xml   # <- Set this to where we find the coverage data.
            #    The path is relative to the current directory.
            format: clover
